apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-deployment  
  labels:
    app: campus 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campus      
  template:
    metadata:
      labels:
        app: campus  
    spec:
      containers:
      - name: campus-container      
        image: campus-image:testing   # Update with registry path, if using ACR or Docker Hub
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: campus-config    # Ensure the configMap name reflects 'campus' if necessary
              key: environment
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
