apiVersion: v1
kind: Service
metadata:
  name: campus-service
spec:
  selector:
    app: campus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # or ClusterIP if only internal access is needed
